site_name: GRASPED Software Systems
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - User Guides:
      - Data Processing Tools: user/data_processing_tools
      - Diwata Browser for QGIS: user/diwata_browser_qgis
      - Operations Software (Users): user/operations_software
      - Operations Software (Admins): user/operations_software_admin
      - PR Site: user/pr_site
  - Technical Guides:
      - Image Browser: technical/image_browser
      - Operations Software: technical/operations_software
markdown_extensions:
  - tables
